name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production

    - name: Deploy to production
      # This is a placeholder - replace with your actual deployment method
      run: |
        echo "🚀 Deploying to production..."
        echo "Build artifacts created in dist/"
        echo "Add your deployment commands here (e.g., deploy to Vercel, Netlify, AWS, etc.)"
        
    - name: Create deployment notification
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: context.payload.deployment?.id || 'manual',
            state: 'success',
            environment: 'production',
            description: 'Successfully deployed to production'
          });

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `## 🚨 Deployment Failed
          
          The deployment to production has failed. Please check the logs and fix any issues.
          
          **Commit:** ${context.sha}
          **Workflow:** ${context.workflow}
          **Run:** ${context.runNumber}`;
          
          // You could also send this to Slack, Discord, or email
          console.log(comment);